// Auto-generated from data/approved.csv
// Do not edit this file directly. Run 'npm run build:data' to regenerate.

import type { Resource } from "@/types/resource";

export const resources: Resource[] = [
  {
    "id": "bear",
    "title": "Bear",
    "url": "https://bear.app/",
    "description": "Reduces overwhelm by keeping notes simple and low-friction to capture.",
    "why_it_helps": "Reduces overwhelm by keeping notes simple and low-friction to capture.",
    "category": "tool",
    "support_needs": [
      "working_memory",
      "task_initiation",
      "overwhelm"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "bear.app"
  },
  {
    "id": "finch",
    "title": "Finch",
    "url": "https://finchcare.com/",
    "description": "Supports consistency by making small tasks feel meaningful and trackable.",
    "why_it_helps": "Supports consistency by making small tasks feel meaningful and trackable.",
    "category": "tool",
    "support_needs": [
      "follow_through",
      "low_energy",
      "overwhelm"
    ],
    "sensory_load": "medium",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "finchcare.com"
  },
  {
    "id": "flow-club",
    "title": "Flow Club",
    "url": "https://www.flow.club/",
    "description": "Supports focus and follow-through by adding social accountability without pressure.",
    "why_it_helps": "Supports focus and follow-through by adding social accountability without pressure.",
    "category": "community",
    "support_needs": [
      "focus",
      "follow_through",
      "task_initiation",
      "overwhelm"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "paid",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "flow.club"
  },
  {
    "id": "flowmate",
    "title": "Flowmate",
    "url": "https://flowmate.club/",
    "description": "Improves time awareness by externalizing time with soft cues so you stay grounded.",
    "why_it_helps": "Improves time awareness by externalizing time with soft cues so you stay grounded.",
    "category": "tool",
    "support_needs": [
      "time_blindness",
      "focus",
      "task_initiation"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "flowmate.club"
  },
  {
    "id": "goblin-tools",
    "title": "Goblin Tools",
    "url": "https://goblin.tools/",
    "description": "Reduces overwhelm by turning vague goals into concrete next steps.",
    "why_it_helps": "Reduces overwhelm by turning vague goals into concrete next steps.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "planning",
      "overwhelm",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "goblin.tools"
  },
  {
    "id": "google-calendar",
    "title": "Google Calendar",
    "url": "https://calendar.google.com/",
    "description": "Helps time awareness by externalizing commitments and reminders.",
    "why_it_helps": "Helps time awareness by externalizing commitments and reminders.",
    "category": "tool",
    "support_needs": [
      "time_blindness",
      "planning",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "calendar.google.com"
  },
  {
    "id": "llama-life",
    "title": "Llama Life",
    "url": "https://llamalife.co/",
    "description": "Improves time awareness by pairing tasks with time boxes so you don’t drift.",
    "why_it_helps": "Improves time awareness by pairing tasks with time boxes so you don’t drift.",
    "category": "tool",
    "support_needs": [
      "time_blindness",
      "task_initiation",
      "focus",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "llamalife.co"
  },
  {
    "id": "most-important-task-mit-framework",
    "title": "Most Important Task (MIT) Framework",
    "url": "https://www.larksuite.com/en_us/topics/productivity-glossary/mit-most-important-task",
    "description": "Reduces overwhelm by narrowing focus to what matters most.",
    "why_it_helps": "Reduces overwhelm by narrowing focus to what matters most.",
    "category": "method",
    "support_needs": [
      "prioritization",
      "overwhelm",
      "planning",
      "focus"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "larksuite.com"
  },
  {
    "id": "phone-free-hour",
    "title": "Phone Free Hour",
    "url": "https://phonefreehour.com/",
    "description": "Reduces distractions by creating a clear, bounded commitment window.",
    "why_it_helps": "Reduces distractions by creating a clear, bounded commitment window.",
    "category": "tool",
    "support_needs": [
      "distraction",
      "focus",
      "task_initiation"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "phonefreehour.com"
  },
  {
    "id": "todoist",
    "title": "Todoist",
    "url": "https://todoist.com/",
    "description": "Supports follow-through by capturing tasks quickly and keeping them easy to review daily.",
    "why_it_helps": "Supports follow-through by capturing tasks quickly and keeping them easy to review daily.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "planning",
      "follow_through",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "todoist.com"
  },
  {
    "id": "trello",
    "title": "Trello",
    "url": "https://trello.com/",
    "description": "Supports prioritization by making tasks visible and easy to move through stages.",
    "why_it_helps": "Supports prioritization by making tasks visible and easy to move through stages.",
    "category": "tool",
    "support_needs": [
      "planning",
      "prioritization",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": true,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "trello.com"
  },
  {
    "id": "amazing-marvin",
    "title": "Amazing Marvin",
    "url": "https://amazingmarvin.com/",
    "description": "Lets you tailor structure to your brain when standard to-do apps don’t fit.",
    "why_it_helps": "Lets you tailor structure to your brain when standard to-do apps don’t fit.",
    "category": "tool",
    "support_needs": [
      "planning",
      "prioritization",
      "follow_through"
    ],
    "sensory_load": "medium",
    "setup_effort": "high",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "amazingmarvin.com"
  },
  {
    "id": "asana",
    "title": "Asana",
    "url": "https://asana.com/",
    "description": "Makes responsibilities visible and reduces mental load with clear ownership and due dates.",
    "why_it_helps": "Makes responsibilities visible and reduces mental load with clear ownership and due dates.",
    "category": "tool",
    "support_needs": [
      "planning",
      "prioritization",
      "follow_through",
      "working_memory"
    ],
    "sensory_load": "medium",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "asana.com"
  },
  {
    "id": "before-launcher",
    "title": "Before Launcher",
    "url": "https://beforelabs.com/",
    "description": "Helps focus by simplifying what you see and reducing impulsive app opens.",
    "why_it_helps": "Helps focus by simplifying what you see and reducing impulsive app opens.",
    "category": "tool",
    "support_needs": [
      "distraction",
      "focus",
      "sensory_sensitivity"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "beforelabs.com"
  },
  {
    "id": "brick",
    "title": "Brick",
    "url": "https://getbrick.app/",
    "description": "Supports follow-through by adding a real-world barrier to impulsive phone use.",
    "why_it_helps": "Supports follow-through by adding a real-world barrier to impulsive phone use.",
    "category": "physical",
    "support_needs": [
      "distraction",
      "focus",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "getbrick.app"
  },
  {
    "id": "calm",
    "title": "Calm",
    "url": "https://www.calm.com/",
    "description": "Supports overwhelm management by helping regulate stress and reset attention.",
    "why_it_helps": "Supports overwhelm management by helping regulate stress and reset attention.",
    "category": "content",
    "support_needs": [
      "overwhelm",
      "focus",
      "sensory_sensitivity",
      "low_energy"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "calm.com"
  },
  {
    "id": "chatgpt",
    "title": "ChatGPT",
    "url": "https://chat.openai.com/",
    "description": "Supports task initiation by helping you get unstuck and generate a first draft.",
    "why_it_helps": "Supports task initiation by helping you get unstuck and generate a first draft.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "planning",
      "overwhelm",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "chat.openai.com"
  },
  {
    "id": "clearspace",
    "title": "ClearSpace",
    "url": "https://www.getclearspace.com/",
    "description": "Reduces distractions by interrupting autopilot behavior.",
    "why_it_helps": "Reduces distractions by interrupting autopilot behavior.",
    "category": "tool",
    "support_needs": [
      "distraction",
      "focus",
      "task_initiation"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "getclearspace.com"
  },
  {
    "id": "clickup",
    "title": "ClickUp",
    "url": "https://clickup.com/",
    "description": "Supports follow-through by centralizing tasks, docs, and accountability.",
    "why_it_helps": "Supports follow-through by centralizing tasks, docs, and accountability.",
    "category": "tool",
    "support_needs": [
      "planning",
      "prioritization",
      "follow_through"
    ],
    "sensory_load": "high",
    "setup_effort": "high",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "clickup.com"
  },
  {
    "id": "clockingit",
    "title": "ClockingIT",
    "url": "http://www.clockingit.com/",
    "description": "Supports time awareness by making time spent visible and trackable.",
    "why_it_helps": "Supports time awareness by making time spent visible and trackable.",
    "category": "tool",
    "support_needs": [
      "time_blindness",
      "planning",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "free",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "clockingit.com"
  },
  {
    "id": "cold-turkey",
    "title": "Cold Turkey",
    "url": "https://getcoldturkey.com/",
    "description": "Helps focus by enforcing boundaries even when willpower drops.",
    "why_it_helps": "Helps focus by enforcing boundaries even when willpower drops.",
    "category": "tool",
    "support_needs": [
      "distraction",
      "focus",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "getcoldturkey.com"
  },
  {
    "id": "done-list-framework",
    "title": "Done List Framework",
    "url": "https://www.oliverburkeman.com/donelist",
    "description": "Supports follow-through by making progress visible and motivating.",
    "why_it_helps": "Supports follow-through by making progress visible and motivating.",
    "category": "method",
    "support_needs": [
      "follow_through",
      "overwhelm",
      "task_initiation",
      "low_energy"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "oliverburkeman.com"
  },
  {
    "id": "eye-dropper-chrome-extension",
    "title": "Eye Dropper (Chrome Extension)",
    "url": "https://chromewebstore.google.com/detail/eye-dropper/hmdcmlfkchdmnmnmheododdhjedfccka?hl=en",
    "description": "Reduces friction by making design/dev color selection fast and reliable.",
    "why_it_helps": "Reduces friction by making design/dev color selection fast and reliable.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "chromewebstore.google.com"
  },
  {
    "id": "fantastical",
    "title": "Fantastical",
    "url": "https://flexibits.com/fantastical",
    "description": "Supports planning by making schedules easier to view and manage.",
    "why_it_helps": "Supports planning by making schedules easier to view and manage.",
    "category": "tool",
    "support_needs": [
      "planning",
      "time_blindness",
      "prioritization"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "flexibits.com"
  },
  {
    "id": "fathom",
    "title": "Fathom",
    "url": "https://fathom.video/",
    "description": "Supports memory by capturing key points so you can stay present in the conversation.",
    "why_it_helps": "Supports memory by capturing key points so you can stay present in the conversation.",
    "category": "tool",
    "support_needs": [
      "working_memory",
      "planning",
      "accessibility_support"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "fathom.video"
  },
  {
    "id": "focus-friend",
    "title": "Focus Friend",
    "url": "https://www.yourfocusfriend.com/",
    "description": "Supports task initiation by adding a real start time and a supportive presence.",
    "why_it_helps": "Supports task initiation by adding a real start time and a supportive presence.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "follow_through",
      "focus",
      "overwhelm"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "yourfocusfriend.com"
  },
  {
    "id": "focus-to-do",
    "title": "Focus To-Do",
    "url": "https://www.focustodo.cn/",
    "description": "Improves time awareness by using short work sprints with breaks.",
    "why_it_helps": "Improves time awareness by using short work sprints with breaks.",
    "category": "tool",
    "support_needs": [
      "time_blindness",
      "focus",
      "task_initiation"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "focustodo.cn"
  },
  {
    "id": "focusmate",
    "title": "Focusmate",
    "url": "https://www.focusmate.com/",
    "description": "Supports follow-through by making start times real and socially anchored.",
    "why_it_helps": "Supports follow-through by making start times real and socially anchored.",
    "category": "community",
    "support_needs": [
      "task_initiation",
      "follow_through",
      "focus"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "focusmate.com"
  },
  {
    "id": "focusquest",
    "title": "FocusQuest",
    "url": "https://play.google.com/store/apps/details?id=com.shikudo.focus.study.forest.pomodoro.productivity.hero.rpg.android&hl=en_US",
    "description": "Boosts motivation by turning focus sessions into game progress.",
    "why_it_helps": "Boosts motivation by turning focus sessions into game progress.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "focus",
      "follow_through"
    ],
    "sensory_load": "medium",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "play.google.com"
  },
  {
    "id": "forest",
    "title": "Forest",
    "url": "https://www.forestapp.cc/",
    "description": "Supports task initiation and focus by making distractions feel costly.",
    "why_it_helps": "Supports task initiation and focus by making distractions feel costly.",
    "category": "tool",
    "support_needs": [
      "focus",
      "distraction",
      "task_initiation"
    ],
    "sensory_load": "medium",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "forestapp.cc"
  },
  {
    "id": "freedom",
    "title": "Freedom",
    "url": "https://freedom.to/",
    "description": "Supports focus by removing temptation during deep work windows.",
    "why_it_helps": "Supports focus by removing temptation during deep work windows.",
    "category": "tool",
    "support_needs": [
      "distraction",
      "focus",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "freedom.to"
  },
  {
    "id": "grammarly",
    "title": "Grammarly",
    "url": "https://www.grammarly.com/",
    "description": "Reduces cognitive load by catching errors and suggesting clearer phrasing.",
    "why_it_helps": "Reduces cognitive load by catching errors and suggesting clearer phrasing.",
    "category": "tool",
    "support_needs": [
      "working_memory",
      "overwhelm",
      "accessibility_support"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "grammarly.com"
  },
  {
    "id": "habitica",
    "title": "Habitica",
    "url": "https://habitica.com/static/home",
    "description": "Boosts motivation by making task completion feel rewarding and visible.",
    "why_it_helps": "Boosts motivation by making task completion feel rewarding and visible.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "follow_through",
      "low_energy"
    ],
    "sensory_load": "medium",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "habitica.com"
  },
  {
    "id": "habitshare",
    "title": "HabitShare",
    "url": "https://habitshareapp.com/",
    "description": "Supports follow-through by adding gentle social accountability and visibility.",
    "why_it_helps": "Supports follow-through by adding gentle social accountability and visibility.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "habitshareapp.com"
  },
  {
    "id": "hear-my-name",
    "title": "Hear My Name",
    "url": "https://hearmyname.net/",
    "description": "Supports accessibility by reducing anxiety and friction in introductions and meetings.",
    "why_it_helps": "Supports accessibility by reducing anxiety and friction in introductions and meetings.",
    "category": "tool",
    "support_needs": [
      "accessibility_support",
      "overwhelm"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "hearmyname.net"
  },
  {
    "id": "indyx",
    "title": "IndyX",
    "url": "https://www.myindyx.com/",
    "description": "Reduces overwhelm and decision fatigue by outsourcing planning and structure.",
    "why_it_helps": "Reduces overwhelm and decision fatigue by outsourcing planning and structure.",
    "category": "tool",
    "support_needs": [
      "planning",
      "overwhelm",
      "low_energy"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "myindyx.com"
  },
  {
    "id": "insight-timer",
    "title": "Insight Timer",
    "url": "https://insighttimer.com/",
    "description": "Helps regulate overwhelm and reset attention with guided practices.",
    "why_it_helps": "Helps regulate overwhelm and reset attention with guided practices.",
    "category": "content",
    "support_needs": [
      "overwhelm",
      "focus",
      "sensory_sensitivity",
      "low_energy"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "insighttimer.com"
  },
  {
    "id": "journal-brain-dump",
    "title": "Journal (Brain Dump)",
    "url": "https://en.wikipedia.org/wiki/Journal",
    "description": "Reduces overwhelm by moving thoughts out of your head and onto paper.",
    "why_it_helps": "Reduces overwhelm by moving thoughts out of your head and onto paper.",
    "category": "physical",
    "support_needs": [
      "overwhelm",
      "planning",
      "working_memory",
      "task_initiation",
      "low_energy"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "en.wikipedia.org"
  },
  {
    "id": "lanes",
    "title": "Lanes",
    "url": "https://lanes.io/",
    "description": "Helps prioritize by making work-in-progress limits and next actions visible.",
    "why_it_helps": "Helps prioritize by making work-in-progress limits and next actions visible.",
    "category": "tool",
    "support_needs": [
      "prioritization",
      "planning",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "lanes.io"
  },
  {
    "id": "minimalist-phone",
    "title": "Minimalist Phone",
    "url": "https://minimalistphone.com/",
    "description": "Reduces distraction by removing visual noise and addictive cues.",
    "why_it_helps": "Reduces distraction by removing visual noise and addictive cues.",
    "category": "tool",
    "support_needs": [
      "distraction",
      "sensory_sensitivity",
      "focus"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "minimalistphone.com"
  },
  {
    "id": "monarch-money",
    "title": "Monarch Money",
    "url": "https://www.monarchmoney.com/",
    "description": "Supports planning by making spending patterns visible and trackable.",
    "why_it_helps": "Supports planning by making spending patterns visible and trackable.",
    "category": "tool",
    "support_needs": [
      "planning",
      "prioritization",
      "working_memory"
    ],
    "sensory_load": "medium",
    "setup_effort": "medium",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "monarchmoney.com"
  },
  {
    "id": "motion",
    "title": "Motion",
    "url": "https://www.usemotion.com/",
    "description": "Helps planning by automatically turning tasks into a realistic schedule.",
    "why_it_helps": "Helps planning by automatically turning tasks into a realistic schedule.",
    "category": "tool",
    "support_needs": [
      "planning",
      "prioritization",
      "time_blindness",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "usemotion.com"
  },
  {
    "id": "notion",
    "title": "Notion",
    "url": "https://www.notion.so/",
    "description": "Reduces tool sprawl by keeping planning and documentation in one place.",
    "why_it_helps": "Reduces tool sprawl by keeping planning and documentation in one place.",
    "category": "tool",
    "support_needs": [
      "planning",
      "working_memory",
      "prioritization"
    ],
    "sensory_load": "medium",
    "setup_effort": "high",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "notion.so"
  },
  {
    "id": "obsidian",
    "title": "Obsidian",
    "url": "https://obsidian.md/",
    "description": "Helps working memory by externalizing thoughts and connecting related ideas over time.",
    "why_it_helps": "Helps working memory by externalizing thoughts and connecting related ideas over time.",
    "category": "tool",
    "support_needs": [
      "working_memory",
      "planning",
      "overwhelm"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "free",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "obsidian.md"
  },
  {
    "id": "otter",
    "title": "Otter",
    "url": "https://otter.ai/",
    "description": "Supports accessibility and memory by turning spoken info into searchable notes.",
    "why_it_helps": "Supports accessibility and memory by turning spoken info into searchable notes.",
    "category": "tool",
    "support_needs": [
      "accessibility_support",
      "working_memory",
      "planning"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "otter.ai"
  },
  {
    "id": "perplexity",
    "title": "Perplexity",
    "url": "https://www.perplexity.ai/",
    "description": "Reduces overwhelm by helping you get to key info quickly.",
    "why_it_helps": "Reduces overwhelm by helping you get to key info quickly.",
    "category": "tool",
    "support_needs": [
      "overwhelm",
      "task_initiation",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "perplexity.ai"
  },
  {
    "id": "raycast",
    "title": "Raycast",
    "url": "https://www.raycast.com/",
    "description": "Reduces friction by letting you do common actions without context switching.",
    "why_it_helps": "Reduces friction by letting you do common actions without context switching.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "focus",
      "distraction",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "raycast.com"
  },
  {
    "id": "reclaim",
    "title": "Reclaim",
    "url": "https://reclaim.ai/",
    "description": "Supports planning by turning intentions into real calendar blocks automatically.",
    "why_it_helps": "Supports planning by turning intentions into real calendar blocks automatically.",
    "category": "tool",
    "support_needs": [
      "planning",
      "time_blindness",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "reclaim.ai"
  },
  {
    "id": "rize",
    "title": "Rize",
    "url": "https://rize.io/",
    "description": "Improves time awareness by showing where time actually goes.",
    "why_it_helps": "Improves time awareness by showing where time actually goes.",
    "category": "tool",
    "support_needs": [
      "time_blindness",
      "focus",
      "prioritization"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "rize.io"
  },
  {
    "id": "routinery",
    "title": "Routinery",
    "url": "https://routinery.app/",
    "description": "Supports follow-through by turning routines into a step-by-step flow.",
    "why_it_helps": "Supports follow-through by turning routines into a step-by-step flow.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "follow_through",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "routinery.app"
  },
  {
    "id": "screenzen",
    "title": "ScreenZen",
    "url": "https://www.screenzen.co/",
    "description": "Reduces distraction loops by interrupting automatic app-opening habits.",
    "why_it_helps": "Reduces distraction loops by interrupting automatic app-opening habits.",
    "category": "tool",
    "support_needs": [
      "distraction",
      "focus",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "free",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "screenzen.co"
  },
  {
    "id": "speechify",
    "title": "Speechify",
    "url": "https://speechify.com/",
    "description": "Supports accessibility by allowing you to listen instead of only reading.",
    "why_it_helps": "Supports accessibility by allowing you to listen instead of only reading.",
    "category": "tool",
    "support_needs": [
      "accessibility_support",
      "focus",
      "low_energy",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "speechify.com"
  },
  {
    "id": "structured",
    "title": "Structured",
    "url": "https://www.structured.app/",
    "description": "Improves time awareness by laying out the day in a clear timeline.",
    "why_it_helps": "Improves time awareness by laying out the day in a clear timeline.",
    "category": "tool",
    "support_needs": [
      "time_blindness",
      "planning",
      "follow_through"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "structured.app"
  },
  {
    "id": "sunsama",
    "title": "Sunsama",
    "url": "https://www.sunsama.com/",
    "description": "Supports planning and prioritization by forcing realistic daily scope.",
    "why_it_helps": "Supports planning and prioritization by forcing realistic daily scope.",
    "category": "tool",
    "support_needs": [
      "planning",
      "prioritization",
      "time_blindness",
      "overwhelm"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "sunsama.com"
  },
  {
    "id": "text-blaze",
    "title": "Text Blaze",
    "url": "https://blaze.today/",
    "description": "Reduces working memory load by turning repeated text into quick shortcuts.",
    "why_it_helps": "Reduces working memory load by turning repeated text into quick shortcuts.",
    "category": "tool",
    "support_needs": [
      "working_memory",
      "task_initiation",
      "focus",
      "accessibility_support"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "blaze.today"
  },
  {
    "id": "toggl-track",
    "title": "Toggl Track",
    "url": "https://toggl.com/track/",
    "description": "Builds time awareness by revealing patterns and realistic estimates.",
    "why_it_helps": "Builds time awareness by revealing patterns and realistic estimates.",
    "category": "tool",
    "support_needs": [
      "time_blindness",
      "planning",
      "prioritization"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "toggl.com"
  },
  {
    "id": "visual-timer-physical",
    "title": "Visual Timer (Physical)",
    "url": "https://en.wikipedia.org/wiki/Visual_timer",
    "description": "Improves time awareness by making remaining time easy to see at a glance.",
    "why_it_helps": "Improves time awareness by making remaining time easy to see at a glance.",
    "category": "physical",
    "support_needs": [
      "time_blindness",
      "focus",
      "task_initiation",
      "accessibility_support"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "en.wikipedia.org"
  },
  {
    "id": "voicenotes",
    "title": "Voicenotes",
    "url": "https://voicenotes.com/",
    "description": "Helps task initiation by making idea capture effortless when typing feels too hard.",
    "why_it_helps": "Helps task initiation by making idea capture effortless when typing feels too hard.",
    "category": "tool",
    "support_needs": [
      "task_initiation",
      "working_memory",
      "low_energy",
      "accessibility_support"
    ],
    "sensory_load": "low",
    "setup_effort": "low",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "voicenotes.com"
  },
  {
    "id": "waybetter",
    "title": "Waybetter",
    "url": "https://waybetter.com/",
    "description": "Supports follow-through by adding accountability and a clear goal window.",
    "why_it_helps": "Supports follow-through by adding accountability and a clear goal window.",
    "category": "community",
    "support_needs": [
      "task_initiation",
      "follow_through"
    ],
    "sensory_load": "medium",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "waybetter.com"
  },
  {
    "id": "whering",
    "title": "Whering",
    "url": "https://whering.co.uk/",
    "description": "Reduces decision fatigue by helping you plan outfits ahead of time.",
    "why_it_helps": "Reduces decision fatigue by helping you plan outfits ahead of time.",
    "category": "tool",
    "support_needs": [
      "planning",
      "overwhelm",
      "working_memory",
      "low_energy"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "freemium",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "whering.co.uk"
  },
  {
    "id": "ynab-you-need-a-budget",
    "title": "YNAB (You Need A Budget)",
    "url": "https://www.ynab.com/",
    "description": "Reduces overwhelm by creating a clear plan for money and upcoming expenses.",
    "why_it_helps": "Reduces overwhelm by creating a clear plan for money and upcoming expenses.",
    "category": "tool",
    "support_needs": [
      "planning",
      "overwhelm",
      "working_memory"
    ],
    "sensory_load": "low",
    "setup_effort": "medium",
    "price_type": "paid",
    "featured": false,
    "affiliate_url": null,
    "is_affiliate": false,
    "domain": "ynab.com"
  }
];
